### ISSUE TITLE
What is the dimension of the learnable feature grid?

### ISSUE THREAD

**Issue by cwchenwang** [MrTornado24/FENeRF#1]
Thanks for your excellent work! Curious about the details of the learnable feature grid (e_coord), what is the dimension of it and do you keep it the same dimension when rendering images of different resolutions?

Looking forward to your reply.

**Comment by MrTornado24** [comment]
In our paper, the learnable feature grid is designed as a 32-channel 3D volume with a resolution of 96<sup>3</sup>. We keep it the same resolution for different image sizes.

**Comment by cwchenwang** [comment]
@MrTornado24 Thanks for your explanation. Would the 96^3 grid limit the resolution of synthesized images (e.g. poor results on 256x256)?

**Comment by MrTornado24** [comment]
@cwchenwang You can try to use a smaller grid size but the feature grid is not the bootle neck of rendering resolution in our case. To render higher resolution images you can use 2D superresolution networks instead of the pure nerf architecture in FENeRF.
