### ISSUE TITLE
How to open .mrc file?

### ISSUE THREAD

**Issue by ryanqiutu** [MrTornado24/FENeRF#10]
Dear Author:
    Great work!!! But How can I open the .mrc file?

**Comment by MrTornado24** [comment]
We visualize our .mrc shape files with [UCSF Chimerax](https://www.cgl.ucsf.edu/chimerax/).

To visualize a shape in ChimeraX do the following:
1. Import the `.mrc` file with `File > Open`
1. Find the selected shape in the Volume Viewer tool
    1. The Volume Viewer tool is located under `Tools > Volume Data > Volume Viewer`
1. Change volume type to "Surface"
1. Change level set to about 30 (or other values depending on objects)

**Comment by ryanqiutu** [comment]
Thanks a lot as the problem has troubled me for a long time!!!

**Comment by ryanqiutu** [comment]
One more question. Can I transfer the shape latent to segmap as input, just like SofGan?

**Comment by MrTornado24** [comment]
I'm afraid not. The modulation methods in FENeRF and SofGAN are different.

**Comment by ryanqiutu** [comment]
Can we link the segmap and the modulation methods in FENeRF by adding an encoder which can transfer the segmap to a latent? If this succeeds, gan inversion and segmap editting will be simplier.

**Comment by MrTornado24** [comment]
Great idea. It seems to be similar to our newest paper: [IDE-3D](https://arxiv.org/abs/2205.15517) accepted by SIGGRAPH Asia 2022. We will release its code and project page soon. Welcome to take a look.
