### ISSUE TITLE
poor performance of the Inversion

### ISSUE THREAD

**Issue by s1752729916** [MrTornado24/FENeRF#15]
请问在用新的portrait进行Inversion的时候，渲染出来的结果很差：
`python inverse_render_double_semantic.py exp_name 、/checkpoint/315000_generator.pth --image_path /dataset/cnn/0/com_imgs/0.jpg --seg_path /dataset/cnn/0/parsing_celebahq/masks1024x1024/0.jpg --background_mask --image_size 128 --latent_normalize --lambda_seg 1. --lambda_img 0.2 --lambda_percept 1. --lock_view_dependence True --recon
`
其中的image和mask如下图所示：

<img src="https://user-images.githubusercontent.com/42924289/203485820-38aa4eec-f6bc-4404-8958-7a5ac8b5ca4b.jpg" alt="cat-shape" width=200 /><img src="https://user-images.githubusercontent.com/42924289/203485830-2bdedfa0-8026-4776-9786-b98da58fdee4.jpg" alt="cat-shape" width=200 /><img src="https://user-images.githubusercontent.com/42924289/203485833-ee1eedcc-88a6-44f8-a442-06be9311e183.jpg" alt="cat-shape" width=200 />

但是渲染出来的结果

是我哪里搞错了吗？
<img src="https://user-images.githubusercontent.com/42924289/203486209-a7eb83e7-87a8-4949-a3ad-40fe89ecd5f5.jpg" alt="cat-shape" width=200 /><img src="https://user-images.githubusercontent.com/42924289/203486211-4e948522-88dc-4f61-afc7-35a678a84e64.jpg" alt="cat-shape" width=200 />

**Comment by MrTornado24** [comment]
Hi, you need to align and crop raw images into the CelebA format before inverse rendering. Please refer to https://github.com/LynnHo/HD-CelebA-Cropper to preprocess your images.
