### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by loboere** [MrTornado24/FENeRF#6]
when i run the script to invert an image nothing seems to happen

!python inverse_render_double_semantic.py exp_name /content/FENeRF/wo_latent_grid/200000_generator.pth --image_path data/examples/image.jpg --seg_path data/examples/mask_edit.png --background_mask --image_size 128 --latent_normalize --lambda_seg 1. --lambda_img 0 --lambda_percept 0 --lock_view_dependence True --recon --load_checkpoint True --checkpoint_path freq_phase_offset_$exp_name.pth

```
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.0], spatial [off]
Loading model from: /usr/local/lib/python3.7/dist-packages/lpips/weights/v0.0/vgg.pth
/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
```

**Comment by MrTornado24** [comment]
Hi, the command you show is to edit a real image. It won't work because it cannot find "freq_phase_offset_$exp_name.pth".    You should fill this position by the checkpoint's name which you obtain in the last step.

**Comment by loboere** [comment]
even deleting that part nothing happens

!python inverse_render_double_semantic.py exp_name /content/FENeRF/wo_latent_grid/200000_generator.pth --image_path data/examples/image.jpg --seg_path data/examples/mask.png --background_mask --image_size 128 --latent_normalize --lambda_seg 1. --lambda_img 0.2 --lambda_percept 1. --lock_view_dependence True --recon
