### ISSUE TITLE
run_UI.py could not work

### ISSUE THREAD

**Issue by JunshenZheng** [MrTornado24/FENeRF#8]
when I try to run run_UI.py，something wrong happens. 

QObject::moveToThread: Current thread (0x5555f1280ce0) is not the object's thread (0x5555f3a25330).
Cannot move to target thread (0x5555f1280ce0)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/junshen/anaconda3/envs/fenerf/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

**Comment by MrTornado24** [comment]
Hi, the error may be caused by Pyqt5 installation. You may refer to [some blogs](https://blog.csdn.net/qq_49641239/article/details/112303826?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&utm_relevant_index=21).

**Comment by JunshenZheng** [comment]
> Hi, the error may be caused by Pyqt5 installation. You may refer to [some blogs](https://blog.csdn.net/qq_49641239/article/details/112303826?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&utm_relevant_index=21).

I try the method but still coundn't work. Could you tell me the version of python , opencv and pyqt5 which you use? Thanks!

**Comment by MrTornado24** [comment]
> > Hi, the error may be caused by Pyqt5 installation. You may refer to [some blogs](https://blog.csdn.net/qq_49641239/article/details/112303826?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&utm_relevant_index=21).
> 
> I try the method but still coundn't work. Could you tell me the version of python , opencv and pyqt5 which you use? Thanks!

Python: 3.9
opencv: 4.5.5.64
pyqt5: 5.12.3

**Comment by ZziTaiLeo** [comment]
> > > Hi, the error may be caused by Pyqt5 installation. You may refer to [some blogs](https://blog.csdn.net/qq_49641239/article/details/112303826?spm=1001.2101.3001.6650.12&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-12-112303826-blog-107212845.pc_relevant_multi_platform_whitelistv1&utm_relevant_index=21).
> > 
> > 
> > I try the method but still coundn't work. Could you tell me the version of python , opencv and pyqt5 which you use? Thanks!
> 
> Python: 3.9 opencv: 4.5.5.64 pyqt5: 5.12.3

I use pip to install these packages, but it still couldn't work, Did you use conda?
