### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by c1a1o1** [MrTornado24/FENeRF#9]
D:\anaconda\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "D:/work/vgan/FENeRF-main/inverse_render_double_semantic.py", line 582, in <module>
    checkpoint_path = run_inverse_render(opt, opt.image_path, opt.seg_path)
  File "D:/work/vgan/FENeRF-main/inverse_render_double_semantic.py", line 404, in run_inverse_render
    loss += opt.lambda_norm * norm_loss
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by MrTornado24** [comment]
Hi, what value did you set to lambda_norm? Please make sure it is a float type value. I guess one simple way is to change `loss += opt.lambda_norm * norm_loss` into `loss += float(opt.lambda_norm) * norm_loss`
